# config.yaml
project_name: "LaTeXProject"
mode: "project"

input:
  dir: "./demo/demo_project"         # for mode=project

output:
  dir: "./output"
  compile: true

translation:
  target_lang: "Chinese"
  chunk_size: 3800
  use_cot: false
  fix_hyphen: true
  fix_command_adhesion: true

llm:
  backend: "aliyun"
  model: "qwen-max"
  api_key: <-- replace with your own api key -->
  base_url: "https://dashscope.aliyuncs.com/api/v1"
  temperature: 0.1
  top_p: 0.9
  max_concurrent: 15
  max_retries: 3